-- =====================================================================
-- RIZZ ACADEMY: alle kaarten (126 kaarten)
-- 13 vrienden x 9 kaarten (slot 1-6 common, 7-8 epic, 9 legendary)
-- + 9 Detention-kaarten (troostkaarten, rarity 'cat').
--
-- Gebruik: Supabase -> SQL Editor -> nieuwe query -> dit VOLLEDIGE bestand plakken -> Run.
-- Kies bij de waarschuwing "Run without RLS".
-- Veilig om opnieuw uit te voeren: bestaande kaarten worden bijgewerkt, niet dubbel aangemaakt.
-- Afbeeldingen: cards/<naam>-<slot>.jpg (zonder afbeelding toont de site een varsity-letter).
-- Gegenereerd door tools/maak-kaarten.py.
-- =====================================================================
insert into public.cards (person, slot, name, rarity, hp, attack, defense, image_url, flavor_text, special_name, special_desc, special_power) values
  ('Arthuur', 1, 'The Lens', 'common', 65, 17, 13, 'cards/arthuur-1.jpg', 'Too close? You''re not close enough.', null, null, null),
  ('Arthuur', 2, 'Stock Photo Guy', 'common', 71, 23, 16, 'cards/arthuur-2.jpg', 'Licensed. Not for resale.', null, null, null),
  ('Arthuur', 3, 'The Night Shift', 'common', 68, 20, 18, 'cards/arthuur-3.jpg', 'Clocks in at midnight. Never clocks out.', null, null, null),
  ('Arthuur', 4, 'The Stare-Down', 'common', 57, 24, 17, 'cards/arthuur-4.jpg', 'Blinked first? You lose.', null, null, null),
  ('Arthuur', 5, 'The Aloha Shirt', 'common', 63, 17, 14, 'cards/arthuur-5.jpg', 'Out of office. Permanently.', null, null, null),
  ('Arthuur', 6, 'Poker Face', 'common', 62, 20, 11, 'cards/arthuur-6.jpg', 'You''ll never know my hand.', null, null, null),
  ('Arthuur', 7, 'Front Row', 'epic', 87, 29, 21, 'cards/arthuur-7.jpg', 'Loudest man in the building.', null, null, null),
  ('Arthuur', 8, 'The Sommelier', 'epic', 80, 24, 22, 'cards/arthuur-8.jpg', 'I don''t taste. I finish.', null, null, null),
  ('Arthuur', 9, 'The Apron', 'legendary', 96, 39, 24, 'cards/arthuur-9.jpg', 'Nothing to hide. Literally.', 'Apron Drop', 'Pure confidence. The opponent looks away first.', 55),
  ('Casper', 1, 'Breaking News', 'common', 58, 16, 15, 'cards/casper-1.jpg', 'Woke up. Chose violence.', null, null, null),
  ('Casper', 2, 'The Landlord', 'common', 67, 17, 14, 'cards/casper-2.jpg', 'Last call is when I say so.', null, null, null),
  ('Casper', 3, 'The Tiny Hat', 'common', 66, 20, 15, 'cards/casper-3.jpg', 'Small hat. Big reputation.', null, null, null),
  ('Casper', 4, 'The Gym Rat', 'common', 57, 17, 11, 'cards/casper-4.jpg', 'Shirt optional. Gains mandatory.', null, null, null),
  ('Casper', 5, 'Hard Hat', 'common', 75, 17, 10, 'cards/casper-5.jpg', 'Safety first. Party second. Barely.', null, null, null),
  ('Casper', 6, 'The Tab', 'common', 56, 18, 15, 'cards/casper-6.jpg', 'Put it on my name. Everyone knows it.', null, null, null),
  ('Casper', 7, 'King of the Hill', 'epic', 90, 27, 21, 'cards/casper-7.jpg', 'Climbed it. Owns it.', null, null, null),
  ('Casper', 8, 'The Fairy Godfather', 'epic', 91, 26, 23, 'cards/casper-8.jpg', 'Grants wishes. Mostly rounds.', null, null, null),
  ('Casper', 9, 'The Box', 'legendary', 107, 33, 23, 'cards/casper-9.jpg', 'What''s inside? Not your business.', 'Lockbox', 'Nobody knows what''s in it. Nobody gets past it.', 47),
  ('Gerben', 1, 'The Miner', 'common', 55, 22, 13, 'cards/gerben-1.jpg', 'Digs deep. Finds holos.', null, null, null),
  ('Gerben', 2, 'Bubble Boss', 'common', 75, 19, 13, 'cards/gerben-2.jpg', 'Runs the place from the tub.', null, null, null),
  ('Gerben', 3, 'The Sheriff', 'common', 62, 22, 18, 'cards/gerben-3.jpg', 'New sheriff in town. Same old rules.', null, null, null),
  ('Gerben', 4, 'The Collector', 'common', 71, 19, 10, 'cards/gerben-4.jpg', 'Started young. Never stopped.', null, null, null),
  ('Gerben', 5, 'The Nose', 'common', 58, 14, 11, 'cards/gerben-5.jpg', 'Smells weakness from ten meters.', null, null, null),
  ('Gerben', 6, 'Camp Leader', 'common', 60, 24, 11, 'cards/gerben-6.jpg', 'Everybody follows. Nobody asks why.', null, null, null),
  ('Gerben', 7, 'The Wise Man', 'epic', 90, 26, 17, 'cards/gerben-7.jpg', 'Came bearing gifts. Left with the room.', null, null, null),
  ('Gerben', 8, 'El Tequila', 'epic', 78, 26, 21, 'cards/gerben-8.jpg', 'One shot. Zero regrets.', null, null, null),
  ('Gerben', 9, 'The Red Cape', 'legendary', 110, 40, 22, 'cards/gerben-9.jpg', 'Red means go.', 'Matador', 'Steps aside. The opponent charges into nothing.', 49),
  ('Jakov', 1, 'The Wipeout', 'common', 65, 14, 10, 'cards/jakov-1.jpg', 'Fell hard. Got up harder.', null, null, null),
  ('Jakov', 2, 'The Hood', 'common', 62, 18, 12, 'cards/jakov-2.jpg', 'Hood up. Talking down.', null, null, null),
  ('Jakov', 3, 'The Smirk', 'common', 67, 23, 15, 'cards/jakov-3.jpg', 'Already knows how this ends.', null, null, null),
  ('Jakov', 4, 'Stadium Mode', 'common', 56, 20, 15, 'cards/jakov-4.jpg', 'Ninety minutes. Zero chill.', null, null, null),
  ('Jakov', 5, 'The Rookie', 'common', 57, 18, 16, 'cards/jakov-5.jpg', 'Pro since day one.', null, null, null),
  ('Jakov', 6, 'Dead Center', 'common', 59, 17, 13, 'cards/jakov-6.jpg', 'Always in the middle of it.', null, null, null),
  ('Jakov', 7, 'Track Beast', 'epic', 84, 27, 19, 'cards/jakov-7.jpg', 'Laps you. Twice.', null, null, null),
  ('Jakov', 8, 'The Glitch', 'epic', 89, 32, 24, 'cards/jakov-8.jpg', 'Can''t be patched.', null, null, null),
  ('Jakov', 9, 'The Bare Cyclist', 'legendary', 108, 38, 23, 'cards/jakov-9.jpg', 'Carbon frame. Zero clothes.', 'Wheel Shield', 'Blocks every attack with the back wheel.', 47),
  ('Jules', 1, 'The BeReal', 'common', 61, 17, 16, 'cards/jules-1.jpg', '6:30 AM. Still standing.', null, null, null),
  ('Jules', 2, 'Bucket List', 'common', 58, 15, 18, 'cards/jules-2.jpg', 'Ordered a cocktail. Got a bucket. Finished it.', null, null, null),
  ('Jules', 3, 'The Close Talker', 'common', 65, 18, 13, 'cards/jules-3.jpg', 'Personal space is a suggestion.', null, null, null),
  ('Jules', 4, 'The Elf', 'common', 58, 18, 15, 'cards/jules-4.jpg', 'Delivers. Every season.', null, null, null),
  ('Jules', 5, 'The Chef', 'common', 63, 22, 15, 'cards/jules-5.jpg', 'Kitchen''s closed. He''s still cooking.', null, null, null),
  ('Jules', 6, 'Empty Pockets', 'common', 56, 21, 17, 'cards/jules-6.jpg', 'Rich in spirit. Broke in cash.', null, null, null),
  ('Jules', 7, 'The Champion', 'epic', 84, 24, 23, 'cards/jules-7.jpg', 'Won once. Never forgot.', null, null, null),
  ('Jules', 8, 'Festival Fit', 'epic', 92, 30, 22, 'cards/jules-8.jpg', 'Leopard print. Zero fear.', null, null, null),
  ('Jules', 9, 'The Sprinkler', 'legendary', 101, 38, 27, 'cards/jules-9.jpg', 'Waters the hedge. Drowns the competition.', 'Hose Blast', 'Washes the opponent off the field.', 55),
  ('Luca', 1, 'The Lollipop', 'common', 60, 23, 12, 'cards/luca-1.jpg', 'Sweet on the outside.', null, null, null),
  ('Luca', 2, 'The Shave', 'common', 55, 24, 16, 'cards/luca-2.jpg', 'Clean cut. Sharp edge.', null, null, null),
  ('Luca', 3, 'The Catalog Model', 'common', 69, 15, 10, 'cards/luca-3.jpg', 'Only one angle. The right one.', null, null, null),
  ('Luca', 4, 'Room Service', 'common', 59, 22, 16, 'cards/luca-4.jpg', 'Two cold ones. Delivered.', null, null, null),
  ('Luca', 5, 'Late Arrival', 'common', 62, 14, 13, 'cards/luca-5.jpg', 'The party starts when I walk in.', null, null, null),
  ('Luca', 6, 'The Rosé Rebel', 'common', 69, 23, 12, 'cards/luca-6.jpg', 'Glasses are for amateurs.', null, null, null),
  ('Luca', 7, 'Background Boss', 'epic', 88, 29, 23, 'cards/luca-7.jpg', 'Even in the back, he''s the main character.', null, null, null),
  ('Luca', 8, 'Birthday King', 'epic', 87, 31, 24, 'cards/luca-8.jpg', 'Every day is his day.', null, null, null),
  ('Luca', 9, 'The Sunflower', 'legendary', 109, 34, 26, 'cards/luca-9.jpg', 'Doesn''t need clothes. Needs sunlight.', 'Bloom', 'Opens up and blinds the whole field.', 48),
  ('Seppe', 1, 'The Thinker', 'common', 72, 23, 12, 'cards/seppe-1.jpg', 'Already three moves ahead.', null, null, null),
  ('Seppe', 2, 'The Lampshade', 'common', 57, 21, 18, 'cards/seppe-2.jpg', 'Lights up every party.', null, null, null),
  ('Seppe', 3, 'The Battle Cry', 'common', 57, 23, 11, 'cards/seppe-3.jpg', 'Heard from three streets away.', null, null, null),
  ('Seppe', 4, 'The Flow', 'common', 55, 24, 16, 'cards/seppe-4.jpg', 'Hair this good is a full-time job.', null, null, null),
  ('Seppe', 5, 'The Bubbly', 'common', 69, 22, 13, 'cards/seppe-5.jpg', 'Two bottles. Both mine.', null, null, null),
  ('Seppe', 6, 'Cold One', 'common', 61, 21, 12, 'cards/seppe-6.jpg', 'Pose first. Drink after.', null, null, null),
  ('Seppe', 7, 'The Dress Code', 'epic', 89, 27, 20, 'cards/seppe-7.jpg', 'Rules are for the guest list.', null, null, null),
  ('Seppe', 8, 'The CEO', 'epic', 88, 29, 20, 'cards/seppe-8.jpg', 'Open to work. Closing deals.', null, null, null),
  ('Seppe', 9, 'The Photographer', 'legendary', 107, 32, 25, 'cards/seppe-9.jpg', 'Somebody had to take the pictures.', 'Crate Throne', 'Sits on his throne while others do the work.', 48),
  ('Stan Lavaert', 1, 'Bottle Service', 'common', 62, 15, 15, 'cards/stan-lavaert-1.jpg', 'Glasses are for guests.', null, null, null),
  ('Stan Lavaert', 2, 'The Headliner', 'common', 56, 22, 11, 'cards/stan-lavaert-2.jpg', 'Carries the night. Every night.', null, null, null),
  ('Stan Lavaert', 3, 'Ultra Since Birth', 'common', 73, 16, 14, 'cards/stan-lavaert-3.jpg', 'Blue and black. No discussion.', null, null, null),
  ('Stan Lavaert', 4, 'Matchday', 'common', 74, 22, 17, 'cards/stan-lavaert-4.jpg', 'Ninety minutes of pure faith.', null, null, null),
  ('Stan Lavaert', 5, 'Party Ears', 'common', 67, 18, 18, 'cards/stan-lavaert-5.jpg', 'Ears on. Volume up.', null, null, null),
  ('Stan Lavaert', 6, 'Tuesday Toast', 'common', 60, 20, 11, 'cards/stan-lavaert-6.jpg', 'Any day is a reason.', null, null, null),
  ('Stan Lavaert', 7, 'The Dark Knight', 'epic', 91, 28, 21, 'cards/stan-lavaert-7.jpg', 'Shows up when it gets dark.', null, null, null),
  ('Stan Lavaert', 8, 'The Sniper', 'epic', 87, 29, 18, 'cards/stan-lavaert-8.jpg', 'One shot. One cup.', null, null, null),
  ('Stan Lavaert', 9, 'The Godfather', 'legendary', 102, 34, 28, 'cards/stan-lavaert-9.jpg', 'Doesn''t say much. Doesn''t have to.', 'Cigar Smoke', 'Wraps the whole field in mystery.', 54),
  ('Stan Sabbe', 1, 'The Storm', 'common', 69, 19, 16, 'cards/stan-sabbe-1.jpg', 'Smiles through the hurricane.', null, null, null),
  ('Stan Sabbe', 2, 'Mr. Innocent', 'common', 72, 19, 10, 'cards/stan-sabbe-2.jpg', 'No witnesses. No case.', null, null, null),
  ('Stan Sabbe', 3, 'The Party Animal', 'common', 59, 23, 16, 'cards/stan-sabbe-3.jpg', 'Best night of his life. Weekly.', null, null, null),
  ('Stan Sabbe', 4, 'The Close Call', 'common', 66, 21, 14, 'cards/stan-sabbe-4.jpg', 'Too close is just close enough.', null, null, null),
  ('Stan Sabbe', 5, 'Festival Hat', 'common', 66, 20, 15, 'cards/stan-sabbe-5.jpg', 'Hat on. Brain off.', null, null, null),
  ('Stan Sabbe', 6, 'Four Eyes', 'common', 60, 18, 14, 'cards/stan-sabbe-6.jpg', 'Sees everything. Says nothing.', null, null, null),
  ('Stan Sabbe', 7, 'Size XL', 'epic', 85, 30, 17, 'cards/stan-sabbe-7.jpg', 'Shirt XL. Ego XXL.', null, null, null),
  ('Stan Sabbe', 8, 'The Prodigy', 'epic', 89, 28, 22, 'cards/stan-sabbe-8.jpg', 'Posing since before he could walk.', null, null, null),
  ('Stan Sabbe', 9, 'The Handyman', 'legendary', 102, 35, 26, 'cards/stan-sabbe-9.jpg', 'Work clothes not required.', 'Power Drill', 'Drills straight through any defense.', 48),
  ('Thibault', 1, 'King of the Jungle', 'common', 62, 19, 11, 'cards/thibault-1.jpg', 'His forest. His rules.', null, null, null),
  ('Thibault', 2, 'The Lawn Chair', 'common', 65, 15, 16, 'cards/thibault-2.jpg', 'Recovery is part of training.', null, null, null),
  ('Thibault', 3, 'The Tongue', 'common', 62, 15, 11, 'cards/thibault-3.jpg', 'Festival mode. No off switch.', null, null, null),
  ('Thibault', 4, 'The Mugshot', 'common', 63, 14, 17, 'cards/thibault-4.jpg', 'Unbothered. Unbreakable.', null, null, null),
  ('Thibault', 5, 'Road Rage', 'common', 60, 16, 18, 'cards/thibault-5.jpg', 'Waves at everyone. One finger.', null, null, null),
  ('Thibault', 6, 'Thumbs Up', 'common', 70, 17, 17, 'cards/thibault-6.jpg', 'Everything''s under control. Probably.', null, null, null),
  ('Thibault', 7, 'The Bar Baron', 'epic', 91, 27, 18, 'cards/thibault-7.jpg', 'He orders. You pay.', null, null, null),
  ('Thibault', 8, 'American Rizz', 'epic', 87, 26, 20, 'cards/thibault-8.jpg', 'One look. Game over.', null, null, null),
  ('Thibault', 9, 'Midnight Streaker', 'legendary', 97, 38, 27, 'cards/thibault-9.jpg', 'Lost the clothes. Kept the beer.', 'Full Moon', 'Lights up the whole street. Everyone looks away.', 49),
  ('Thomas', 1, 'Round Two', 'common', 73, 22, 15, 'cards/thomas-1.jpg', 'Another one. Obviously.', null, null, null),
  ('Thomas', 2, 'Paparazzi', 'common', 63, 14, 18, 'cards/thomas-2.jpg', 'Always on camera. Never by accident.', null, null, null),
  ('Thomas', 3, 'The Sprint', 'common', 63, 21, 18, 'cards/thomas-3.jpg', 'First in the water. First out.', null, null, null),
  ('Thomas', 4, 'The Rally Driver', 'common', 56, 14, 11, 'cards/thomas-4.jpg', 'Brakes are optional.', null, null, null),
  ('Thomas', 5, 'The Tourist', 'common', 67, 16, 13, 'cards/thomas-5.jpg', 'Seen it. Tasted it. Next.', null, null, null),
  ('Thomas', 6, 'Bedhead', 'common', 58, 23, 16, 'cards/thomas-6.jpg', 'Rolled out of bed. Still won.', null, null, null),
  ('Thomas', 7, 'The Towel', 'epic', 81, 30, 23, 'cards/thomas-7.jpg', 'Fresh out the shower. Still the main event.', null, null, null),
  ('Thomas', 8, 'The Yellow Jersey', 'epic', 91, 30, 24, 'cards/thomas-8.jpg', 'Leads the pack. Always.', null, null, null),
  ('Thomas', 9, 'The Snow Plow', 'legendary', 109, 32, 22, 'cards/thomas-9.jpg', 'Clears the road. Clears the room.', 'Snow Shovel', 'Scoops the opponent off the field in one move.', 52),
  ('Tuur', 1, 'The Plushie King', 'common', 61, 23, 13, 'cards/tuur-1.jpg', 'Every claw machine fears him.', null, null, null),
  ('Tuur', 2, 'Steel Gaze', 'common', 62, 19, 17, 'cards/tuur-2.jpg', 'One look. Total silence.', null, null, null),
  ('Tuur', 3, 'The Chin Guard', 'common', 58, 15, 18, 'cards/tuur-3.jpg', 'Protection is protection.', null, null, null),
  ('Tuur', 4, 'Can Do', 'common', 67, 19, 16, 'cards/tuur-4.jpg', 'Finishes it in one breath.', null, null, null),
  ('Tuur', 5, 'The Selfie', 'common', 62, 19, 16, 'cards/tuur-5.jpg', 'No bad angles.', null, null, null),
  ('Tuur', 6, 'The Snapchat', 'common', 56, 19, 12, 'cards/tuur-6.jpg', 'Sent. Opened. No reply needed.', null, null, null),
  ('Tuur', 7, 'The Waiter', 'epic', 92, 25, 23, 'cards/tuur-7.jpg', 'Your order? Already handled.', null, null, null),
  ('Tuur', 8, 'The Long Straw', 'epic', 88, 26, 19, 'cards/tuur-8.jpg', 'Keeps his distance. Keeps his drink.', null, null, null),
  ('Tuur', 9, 'The Rizz Lord', 'legendary', 100, 36, 23, 'cards/tuur-9.jpg', 'Came with a bandana. Left with a kiss.', 'Lipstick Mark', 'Marks the opponent forever.', 53),
  ('Wout', 1, 'The Shades', 'common', 75, 21, 10, 'cards/wout-1.jpg', 'Can''t see a thing. Looks incredible.', null, null, null),
  ('Wout', 2, 'The Postcard', 'common', 71, 22, 10, 'cards/wout-2.jpg', 'Greetings from wherever he wants.', null, null, null),
  ('Wout', 3, 'Full Moon', 'common', 55, 23, 18, 'cards/wout-3.jpg', 'Shows his best side. Unasked.', null, null, null),
  ('Wout', 4, 'The Clubber', 'common', 56, 19, 16, 'cards/wout-4.jpg', 'Sunglasses at night. On principle.', null, null, null),
  ('Wout', 5, 'The Buzz Cut', 'common', 73, 22, 18, 'cards/wout-5.jpg', 'New cut. Same menace.', null, null, null),
  ('Wout', 6, 'The Crate', 'common', 72, 20, 15, 'cards/wout-6.jpg', 'Where he sits, the crate follows.', null, null, null),
  ('Wout', 7, 'Top Shelf', 'epic', 90, 27, 22, 'cards/wout-7.jpg', 'Pours faster than you drink.', null, null, null),
  ('Wout', 8, 'The Boss', 'epic', 89, 29, 19, 'cards/wout-8.jpg', 'Has a plan. The plan works.', null, null, null),
  ('Wout', 9, 'The Gardener', 'legendary', 96, 33, 22, 'cards/wout-9.jpg', 'Grows things. Breaks things.', 'Wheelbarrow Charge', 'Rolls straight through the opponent.', 49),
  ('Detention', 1, 'Late for Class', 'cat', 40, 13, 11, 'cards/detention-1.jpg', 'Alarm went off. He didn''t.', null, null, null),
  ('Detention', 2, 'The Hangover', 'cat', 40, 14, 12, 'cards/detention-2.jpg', 'Never again. Until Friday.', null, null, null),
  ('Detention', 3, 'Left on Read', 'cat', 45, 13, 8, 'cards/detention-3.jpg', 'Seen 23:41. No reply.', null, null, null),
  ('Detention', 4, 'Phone Confiscated', 'cat', 50, 14, 9, 'cards/detention-4.jpg', 'Back at the end of the year.', null, null, null),
  ('Detention', 5, 'Study Hall', 'cat', 50, 10, 7, 'cards/detention-5.jpg', 'Write it 100 times: solve the Wordle.', null, null, null),
  ('Detention', 6, 'Beer Pong Defeat', 'cat', 41, 13, 10, 'cards/detention-6.jpg', 'Every cup. Every single one.', null, null, null),
  ('Detention', 7, 'Missed the Last Train', 'cat', 50, 10, 9, 'cards/detention-7.jpg', 'Tonight: someone else''s couch.', null, null, null),
  ('Detention', 8, 'Rage Quit', 'cat', 51, 10, 9, 'cards/detention-8.jpg', 'The controller didn''t make it.', null, null, null),
  ('Detention', 9, 'Asleep in Lecture', 'cat', 46, 11, 8, 'cards/detention-9.jpg', 'Woke up in a different class.', null, null, null)
on conflict (person, slot) do update set
  name = excluded.name, rarity = excluded.rarity, hp = excluded.hp, attack = excluded.attack,
  defense = excluded.defense, image_url = excluded.image_url, flavor_text = excluded.flavor_text,
  special_name = excluded.special_name, special_desc = excluded.special_desc, special_power = excluded.special_power;
