-- =====================================================================
-- RIZZ ACADEMY: testkaarten (126 kaarten)
-- 13 vrienden x 9 kaarten (slot 1-6 common, 7-8 epic, 9 legendary)
-- + 9 Detention-kaarten (troostkaarten, rarity 'cat').
--
-- Gebruik: Supabase -> SQL Editor -> nieuwe query -> dit VOLLEDIGE bestand plakken -> Run.
-- Kies bij de waarschuwing "Run without RLS".
-- Veilig om opnieuw uit te voeren: bestaande kaarten worden bijgewerkt, niet dubbel aangemaakt.
--
-- Afbeeldingen: upload ze later naar de map cards/ met exact de naam uit image_url
-- (bv. cards/thomas-1.jpg). Zolang een afbeelding ontbreekt, toont de site een
-- varsity-letter als tijdelijke illustratie.
-- Gegenereerd door tools/maak-kaarten.py.
-- =====================================================================
insert into public.cards (person, slot, name, rarity, hp, attack, defense, image_url, flavor_text, special_name, special_desc, special_power) values
  ('Thomas', 1, 'Rookie Thomas', 'common', 73, 22, 15, 'cards/thomas-1.jpg', 'Weet nog niet waar de aula is, wel waar de bar is.', null, null, null),
  ('Thomas', 2, 'Hall Pass Thomas', 'common', 63, 14, 18, 'cards/thomas-2.jpg', 'Gaat even naar het toilet en komt na een uur terug.', null, null, null),
  ('Thomas', 3, 'Gamer Thomas', 'common', 63, 21, 18, 'cards/thomas-3.jpg', 'Nog één potje. Het is vier uur ''s nachts.', null, null, null),
  ('Thomas', 4, 'Poker Face Thomas', 'common', 56, 14, 11, 'cards/thomas-4.jpg', 'Niemand weet wat hij in handen heeft. Hijzelf ook niet.', null, null, null),
  ('Thomas', 5, 'Keg Stand Thomas', 'common', 67, 16, 13, 'cards/thomas-5.jpg', 'Ondersteboven is ook een standpunt.', null, null, null),
  ('Thomas', 6, 'Night Owl Thomas', 'common', 58, 23, 16, 'cards/thomas-6.jpg', 'Gaat "nog ééntje drinken" en is om zes uur thuis.', null, null, null),
  ('Thomas', 7, 'Prom King Thomas', 'epic', 81, 30, 23, 'cards/thomas-7.jpg', 'Gekroond op het bal en nooit meer afgezet.', null, null, null),
  ('Thomas', 8, 'Dean''s List Thomas', 'epic', 91, 30, 24, 'cards/thomas-8.jpg', 'Hoogste punten, minste slaap.', null, null, null),
  ('Thomas', 9, 'Hall of Fame Thomas', 'legendary', 109, 32, 22, 'cards/thomas-9.jpg', 'Class of 2026.', 'Legendary Rizz', 'Eén blik en het hele café is fan.', 52),
  ('Seppe', 1, 'New Kid Seppe', 'common', 72, 23, 12, 'cards/seppe-1.jpg', 'Stelt zich aan iedereen voor. Twee keer.', null, null, null),
  ('Seppe', 2, 'Class Clown Seppe', 'common', 57, 21, 18, 'cards/seppe-2.jpg', 'Lacht het hardst om zijn eigen grappen.', null, null, null),
  ('Seppe', 3, 'Lag Lord Seppe', 'common', 57, 23, 11, 'cards/seppe-3.jpg', 'Het lag aan de wifi. Het ligt altijd aan de wifi.', null, null, null),
  ('Seppe', 4, 'Dealer Seppe', 'common', 55, 24, 16, 'cards/seppe-4.jpg', 'Wie deelt? Ik deel. Altijd.', null, null, null),
  ('Seppe', 5, 'Beer Pong Seppe', 'common', 69, 22, 13, 'cards/seppe-5.jpg', 'Mikt beter na het derde glas.', null, null, null),
  ('Seppe', 6, 'Dancefloor Seppe', 'common', 61, 21, 12, 'cards/seppe-6.jpg', 'Eerste op de dansvloer, laatste eraf.', null, null, null),
  ('Seppe', 7, 'MVP Seppe', 'epic', 89, 27, 20, 'cards/seppe-7.jpg', 'Most Valuable Partyganger.', null, null, null),
  ('Seppe', 8, 'Frat President Seppe', 'epic', 88, 29, 20, 'cards/seppe-8.jpg', 'Zijn kot, zijn regels.', null, null, null),
  ('Seppe', 9, 'Valedictorian Seppe', 'legendary', 107, 32, 25, 'cards/seppe-9.jpg', 'Class of 2026.', 'Afscheidsspeech', 'Iedereen huilt, ook de tegenstander.', 48),
  ('Jules', 1, 'Freshman Jules', 'common', 61, 17, 16, 'cards/jules-1.jpg', 'Eerste dag op de campus en nu al verdwaald.', null, null, null),
  ('Jules', 2, 'Back Row Jules', 'common', 58, 15, 18, 'cards/jules-2.jpg', 'Zit altijd achteraan. Voor het overzicht, zegt hij.', null, null, null),
  ('Jules', 3, 'Respawn Jules', 'common', 65, 18, 13, 'cards/jules-3.jpg', 'Staat sneller op in de game dan in het echt.', null, null, null),
  ('Jules', 4, 'Card Shark Jules', 'common', 58, 18, 15, 'cards/jules-4.jpg', 'Heeft altijd nog een troef achter de hand.', null, null, null),
  ('Jules', 5, 'Jules on Tap', 'common', 63, 22, 15, 'cards/jules-5.jpg', 'Altijd vers getapt, nooit lauw.', null, null, null),
  ('Jules', 6, 'Afterparty Jules', 'common', 56, 21, 17, 'cards/jules-6.jpg', 'Het feest begint pas als hij binnenkomt.', null, null, null),
  ('Jules', 7, 'Varsity Captain Jules', 'epic', 84, 24, 23, 'cards/jules-7.jpg', 'Draagt de jas, draagt het team.', null, null, null),
  ('Jules', 8, 'Homecoming Hero Jules', 'epic', 92, 30, 22, 'cards/jules-8.jpg', 'Scoort op het veld en daarbuiten.', null, null, null),
  ('Jules', 9, 'Rizz Royalty Jules', 'legendary', 101, 38, 27, 'cards/jules-9.jpg', 'Class of 2026.', 'Royal Decree', 'Wat hij zegt, gebeurt.', 55),
  ('Arthuur', 1, 'Rookie Arthuur', 'common', 65, 17, 13, 'cards/arthuur-1.jpg', 'Weet nog niet waar de aula is, wel waar de bar is.', null, null, null),
  ('Arthuur', 2, 'Hall Pass Arthuur', 'common', 71, 23, 16, 'cards/arthuur-2.jpg', 'Gaat even naar het toilet en komt na een uur terug.', null, null, null),
  ('Arthuur', 3, 'Gamer Arthuur', 'common', 68, 20, 18, 'cards/arthuur-3.jpg', 'Nog één potje. Het is vier uur ''s nachts.', null, null, null),
  ('Arthuur', 4, 'Poker Face Arthuur', 'common', 57, 24, 17, 'cards/arthuur-4.jpg', 'Niemand weet wat hij in handen heeft. Hijzelf ook niet.', null, null, null),
  ('Arthuur', 5, 'Keg Stand Arthuur', 'common', 63, 17, 14, 'cards/arthuur-5.jpg', 'Ondersteboven is ook een standpunt.', null, null, null),
  ('Arthuur', 6, 'Night Owl Arthuur', 'common', 62, 20, 11, 'cards/arthuur-6.jpg', 'Gaat "nog ééntje drinken" en is om zes uur thuis.', null, null, null),
  ('Arthuur', 7, 'Prom King Arthuur', 'epic', 87, 29, 21, 'cards/arthuur-7.jpg', 'Gekroond op het bal en nooit meer afgezet.', null, null, null),
  ('Arthuur', 8, 'Dean''s List Arthuur', 'epic', 80, 24, 22, 'cards/arthuur-8.jpg', 'Hoogste punten, minste slaap.', null, null, null),
  ('Arthuur', 9, 'Hall of Fame Arthuur', 'legendary', 96, 39, 24, 'cards/arthuur-9.jpg', 'Class of 2026.', 'Legendary Rizz', 'Eén blik en het hele café is fan.', 55),
  ('Tuur', 1, 'New Kid Tuur', 'common', 61, 23, 13, 'cards/tuur-1.jpg', 'Stelt zich aan iedereen voor. Twee keer.', null, null, null),
  ('Tuur', 2, 'Class Clown Tuur', 'common', 62, 19, 17, 'cards/tuur-2.jpg', 'Lacht het hardst om zijn eigen grappen.', null, null, null),
  ('Tuur', 3, 'Lag Lord Tuur', 'common', 58, 15, 18, 'cards/tuur-3.jpg', 'Het lag aan de wifi. Het ligt altijd aan de wifi.', null, null, null),
  ('Tuur', 4, 'Dealer Tuur', 'common', 67, 19, 16, 'cards/tuur-4.jpg', 'Wie deelt? Ik deel. Altijd.', null, null, null),
  ('Tuur', 5, 'Beer Pong Tuur', 'common', 62, 19, 16, 'cards/tuur-5.jpg', 'Mikt beter na het derde glas.', null, null, null),
  ('Tuur', 6, 'Dancefloor Tuur', 'common', 56, 19, 12, 'cards/tuur-6.jpg', 'Eerste op de dansvloer, laatste eraf.', null, null, null),
  ('Tuur', 7, 'MVP Tuur', 'epic', 92, 25, 23, 'cards/tuur-7.jpg', 'Most Valuable Partyganger.', null, null, null),
  ('Tuur', 8, 'Frat President Tuur', 'epic', 88, 26, 19, 'cards/tuur-8.jpg', 'Zijn kot, zijn regels.', null, null, null),
  ('Tuur', 9, 'Valedictorian Tuur', 'legendary', 100, 36, 23, 'cards/tuur-9.jpg', 'Class of 2026.', 'Afscheidsspeech', 'Iedereen huilt, ook de tegenstander.', 53),
  ('Stan Sabbe', 1, 'Freshman Stan S.', 'common', 69, 19, 16, 'cards/stan-sabbe-1.jpg', 'Eerste dag op de campus en nu al verdwaald.', null, null, null),
  ('Stan Sabbe', 2, 'Back Row Stan S.', 'common', 72, 19, 10, 'cards/stan-sabbe-2.jpg', 'Zit altijd achteraan. Voor het overzicht, zegt hij.', null, null, null),
  ('Stan Sabbe', 3, 'Respawn Stan S.', 'common', 59, 23, 16, 'cards/stan-sabbe-3.jpg', 'Staat sneller op in de game dan in het echt.', null, null, null),
  ('Stan Sabbe', 4, 'Card Shark Stan S.', 'common', 66, 21, 14, 'cards/stan-sabbe-4.jpg', 'Heeft altijd nog een troef achter de hand.', null, null, null),
  ('Stan Sabbe', 5, 'Stan S. on Tap', 'common', 66, 20, 15, 'cards/stan-sabbe-5.jpg', 'Altijd vers getapt, nooit lauw.', null, null, null),
  ('Stan Sabbe', 6, 'Afterparty Stan S.', 'common', 60, 18, 14, 'cards/stan-sabbe-6.jpg', 'Het feest begint pas als hij binnenkomt.', null, null, null),
  ('Stan Sabbe', 7, 'Varsity Captain Stan S.', 'epic', 85, 30, 17, 'cards/stan-sabbe-7.jpg', 'Draagt de jas, draagt het team.', null, null, null),
  ('Stan Sabbe', 8, 'Homecoming Hero Stan S.', 'epic', 89, 28, 22, 'cards/stan-sabbe-8.jpg', 'Scoort op het veld en daarbuiten.', null, null, null),
  ('Stan Sabbe', 9, 'Rizz Royalty Stan S.', 'legendary', 102, 35, 26, 'cards/stan-sabbe-9.jpg', 'Class of 2026.', 'Royal Decree', 'Wat hij zegt, gebeurt.', 48),
  ('Stan Lavaert', 1, 'Rookie Stan L.', 'common', 62, 15, 15, 'cards/stan-lavaert-1.jpg', 'Weet nog niet waar de aula is, wel waar de bar is.', null, null, null),
  ('Stan Lavaert', 2, 'Hall Pass Stan L.', 'common', 56, 22, 11, 'cards/stan-lavaert-2.jpg', 'Gaat even naar het toilet en komt na een uur terug.', null, null, null),
  ('Stan Lavaert', 3, 'Gamer Stan L.', 'common', 73, 16, 14, 'cards/stan-lavaert-3.jpg', 'Nog één potje. Het is vier uur ''s nachts.', null, null, null),
  ('Stan Lavaert', 4, 'Poker Face Stan L.', 'common', 74, 22, 17, 'cards/stan-lavaert-4.jpg', 'Niemand weet wat hij in handen heeft. Hijzelf ook niet.', null, null, null),
  ('Stan Lavaert', 5, 'Keg Stand Stan L.', 'common', 67, 18, 18, 'cards/stan-lavaert-5.jpg', 'Ondersteboven is ook een standpunt.', null, null, null),
  ('Stan Lavaert', 6, 'Night Owl Stan L.', 'common', 60, 20, 11, 'cards/stan-lavaert-6.jpg', 'Gaat "nog ééntje drinken" en is om zes uur thuis.', null, null, null),
  ('Stan Lavaert', 7, 'Prom King Stan L.', 'epic', 91, 28, 21, 'cards/stan-lavaert-7.jpg', 'Gekroond op het bal en nooit meer afgezet.', null, null, null),
  ('Stan Lavaert', 8, 'Dean''s List Stan L.', 'epic', 87, 29, 18, 'cards/stan-lavaert-8.jpg', 'Hoogste punten, minste slaap.', null, null, null),
  ('Stan Lavaert', 9, 'Hall of Fame Stan L.', 'legendary', 102, 34, 28, 'cards/stan-lavaert-9.jpg', 'Class of 2026.', 'Legendary Rizz', 'Eén blik en het hele café is fan.', 54),
  ('Gerben', 1, 'New Kid Gerben', 'common', 55, 22, 13, 'cards/gerben-1.jpg', 'Stelt zich aan iedereen voor. Twee keer.', null, null, null),
  ('Gerben', 2, 'Class Clown Gerben', 'common', 75, 19, 13, 'cards/gerben-2.jpg', 'Lacht het hardst om zijn eigen grappen.', null, null, null),
  ('Gerben', 3, 'Lag Lord Gerben', 'common', 62, 22, 18, 'cards/gerben-3.jpg', 'Het lag aan de wifi. Het ligt altijd aan de wifi.', null, null, null),
  ('Gerben', 4, 'Dealer Gerben', 'common', 71, 19, 10, 'cards/gerben-4.jpg', 'Wie deelt? Ik deel. Altijd.', null, null, null),
  ('Gerben', 5, 'Beer Pong Gerben', 'common', 58, 14, 11, 'cards/gerben-5.jpg', 'Mikt beter na het derde glas.', null, null, null),
  ('Gerben', 6, 'Dancefloor Gerben', 'common', 60, 24, 11, 'cards/gerben-6.jpg', 'Eerste op de dansvloer, laatste eraf.', null, null, null),
  ('Gerben', 7, 'MVP Gerben', 'epic', 90, 26, 17, 'cards/gerben-7.jpg', 'Most Valuable Partyganger.', null, null, null),
  ('Gerben', 8, 'Frat President Gerben', 'epic', 78, 26, 21, 'cards/gerben-8.jpg', 'Zijn kot, zijn regels.', null, null, null),
  ('Gerben', 9, 'Valedictorian Gerben', 'legendary', 110, 40, 22, 'cards/gerben-9.jpg', 'Class of 2026.', 'Afscheidsspeech', 'Iedereen huilt, ook de tegenstander.', 49),
  ('Luca', 1, 'Freshman Luca', 'common', 60, 23, 12, 'cards/luca-1.jpg', 'Eerste dag op de campus en nu al verdwaald.', null, null, null),
  ('Luca', 2, 'Back Row Luca', 'common', 55, 24, 16, 'cards/luca-2.jpg', 'Zit altijd achteraan. Voor het overzicht, zegt hij.', null, null, null),
  ('Luca', 3, 'Respawn Luca', 'common', 69, 15, 10, 'cards/luca-3.jpg', 'Staat sneller op in de game dan in het echt.', null, null, null),
  ('Luca', 4, 'Card Shark Luca', 'common', 59, 22, 16, 'cards/luca-4.jpg', 'Heeft altijd nog een troef achter de hand.', null, null, null),
  ('Luca', 5, 'Luca on Tap', 'common', 62, 14, 13, 'cards/luca-5.jpg', 'Altijd vers getapt, nooit lauw.', null, null, null),
  ('Luca', 6, 'Afterparty Luca', 'common', 69, 23, 12, 'cards/luca-6.jpg', 'Het feest begint pas als hij binnenkomt.', null, null, null),
  ('Luca', 7, 'Varsity Captain Luca', 'epic', 88, 29, 23, 'cards/luca-7.jpg', 'Draagt de jas, draagt het team.', null, null, null),
  ('Luca', 8, 'Homecoming Hero Luca', 'epic', 87, 31, 24, 'cards/luca-8.jpg', 'Scoort op het veld en daarbuiten.', null, null, null),
  ('Luca', 9, 'Rizz Royalty Luca', 'legendary', 109, 34, 26, 'cards/luca-9.jpg', 'Class of 2026.', 'Royal Decree', 'Wat hij zegt, gebeurt.', 48),
  ('Jakov', 1, 'Rookie Jakov', 'common', 65, 14, 10, 'cards/jakov-1.jpg', 'Weet nog niet waar de aula is, wel waar de bar is.', null, null, null),
  ('Jakov', 2, 'Hall Pass Jakov', 'common', 62, 18, 12, 'cards/jakov-2.jpg', 'Gaat even naar het toilet en komt na een uur terug.', null, null, null),
  ('Jakov', 3, 'Gamer Jakov', 'common', 67, 23, 15, 'cards/jakov-3.jpg', 'Nog één potje. Het is vier uur ''s nachts.', null, null, null),
  ('Jakov', 4, 'Poker Face Jakov', 'common', 56, 20, 15, 'cards/jakov-4.jpg', 'Niemand weet wat hij in handen heeft. Hijzelf ook niet.', null, null, null),
  ('Jakov', 5, 'Keg Stand Jakov', 'common', 57, 18, 16, 'cards/jakov-5.jpg', 'Ondersteboven is ook een standpunt.', null, null, null),
  ('Jakov', 6, 'Night Owl Jakov', 'common', 59, 17, 13, 'cards/jakov-6.jpg', 'Gaat "nog ééntje drinken" en is om zes uur thuis.', null, null, null),
  ('Jakov', 7, 'Prom King Jakov', 'epic', 84, 27, 19, 'cards/jakov-7.jpg', 'Gekroond op het bal en nooit meer afgezet.', null, null, null),
  ('Jakov', 8, 'Dean''s List Jakov', 'epic', 89, 32, 24, 'cards/jakov-8.jpg', 'Hoogste punten, minste slaap.', null, null, null),
  ('Jakov', 9, 'Hall of Fame Jakov', 'legendary', 108, 38, 23, 'cards/jakov-9.jpg', 'Class of 2026.', 'Legendary Rizz', 'Eén blik en het hele café is fan.', 47),
  ('Casper', 1, 'New Kid Casper', 'common', 58, 16, 15, 'cards/casper-1.jpg', 'Stelt zich aan iedereen voor. Twee keer.', null, null, null),
  ('Casper', 2, 'Class Clown Casper', 'common', 67, 17, 14, 'cards/casper-2.jpg', 'Lacht het hardst om zijn eigen grappen.', null, null, null),
  ('Casper', 3, 'Lag Lord Casper', 'common', 66, 20, 15, 'cards/casper-3.jpg', 'Het lag aan de wifi. Het ligt altijd aan de wifi.', null, null, null),
  ('Casper', 4, 'Dealer Casper', 'common', 57, 17, 11, 'cards/casper-4.jpg', 'Wie deelt? Ik deel. Altijd.', null, null, null),
  ('Casper', 5, 'Beer Pong Casper', 'common', 75, 17, 10, 'cards/casper-5.jpg', 'Mikt beter na het derde glas.', null, null, null),
  ('Casper', 6, 'Dancefloor Casper', 'common', 56, 18, 15, 'cards/casper-6.jpg', 'Eerste op de dansvloer, laatste eraf.', null, null, null),
  ('Casper', 7, 'MVP Casper', 'epic', 90, 27, 21, 'cards/casper-7.jpg', 'Most Valuable Partyganger.', null, null, null),
  ('Casper', 8, 'Frat President Casper', 'epic', 91, 26, 23, 'cards/casper-8.jpg', 'Zijn kot, zijn regels.', null, null, null),
  ('Casper', 9, 'Valedictorian Casper', 'legendary', 107, 33, 23, 'cards/casper-9.jpg', 'Class of 2026.', 'Afscheidsspeech', 'Iedereen huilt, ook de tegenstander.', 47),
  ('Wout', 1, 'Freshman Wout', 'common', 75, 21, 10, 'cards/wout-1.jpg', 'Eerste dag op de campus en nu al verdwaald.', null, null, null),
  ('Wout', 2, 'Back Row Wout', 'common', 71, 22, 10, 'cards/wout-2.jpg', 'Zit altijd achteraan. Voor het overzicht, zegt hij.', null, null, null),
  ('Wout', 3, 'Respawn Wout', 'common', 55, 23, 18, 'cards/wout-3.jpg', 'Staat sneller op in de game dan in het echt.', null, null, null),
  ('Wout', 4, 'Card Shark Wout', 'common', 56, 19, 16, 'cards/wout-4.jpg', 'Heeft altijd nog een troef achter de hand.', null, null, null),
  ('Wout', 5, 'Wout on Tap', 'common', 73, 22, 18, 'cards/wout-5.jpg', 'Altijd vers getapt, nooit lauw.', null, null, null),
  ('Wout', 6, 'Afterparty Wout', 'common', 72, 20, 15, 'cards/wout-6.jpg', 'Het feest begint pas als hij binnenkomt.', null, null, null),
  ('Wout', 7, 'Varsity Captain Wout', 'epic', 90, 27, 22, 'cards/wout-7.jpg', 'Draagt de jas, draagt het team.', null, null, null),
  ('Wout', 8, 'Homecoming Hero Wout', 'epic', 89, 29, 19, 'cards/wout-8.jpg', 'Scoort op het veld en daarbuiten.', null, null, null),
  ('Wout', 9, 'Rizz Royalty Wout', 'legendary', 96, 33, 22, 'cards/wout-9.jpg', 'Class of 2026.', 'Royal Decree', 'Wat hij zegt, gebeurt.', 49),
  ('Thibault', 1, 'Rookie Thibault', 'common', 62, 19, 11, 'cards/thibault-1.jpg', 'Weet nog niet waar de aula is, wel waar de bar is.', null, null, null),
  ('Thibault', 2, 'Hall Pass Thibault', 'common', 65, 15, 16, 'cards/thibault-2.jpg', 'Gaat even naar het toilet en komt na een uur terug.', null, null, null),
  ('Thibault', 3, 'Gamer Thibault', 'common', 62, 15, 11, 'cards/thibault-3.jpg', 'Nog één potje. Het is vier uur ''s nachts.', null, null, null),
  ('Thibault', 4, 'Poker Face Thibault', 'common', 63, 14, 17, 'cards/thibault-4.jpg', 'Niemand weet wat hij in handen heeft. Hijzelf ook niet.', null, null, null),
  ('Thibault', 5, 'Keg Stand Thibault', 'common', 60, 16, 18, 'cards/thibault-5.jpg', 'Ondersteboven is ook een standpunt.', null, null, null),
  ('Thibault', 6, 'Night Owl Thibault', 'common', 70, 17, 17, 'cards/thibault-6.jpg', 'Gaat "nog ééntje drinken" en is om zes uur thuis.', null, null, null),
  ('Thibault', 7, 'Prom King Thibault', 'epic', 91, 27, 18, 'cards/thibault-7.jpg', 'Gekroond op het bal en nooit meer afgezet.', null, null, null),
  ('Thibault', 8, 'Dean''s List Thibault', 'epic', 87, 26, 20, 'cards/thibault-8.jpg', 'Hoogste punten, minste slaap.', null, null, null),
  ('Thibault', 9, 'Hall of Fame Thibault', 'legendary', 97, 38, 27, 'cards/thibault-9.jpg', 'Class of 2026.', 'Legendary Rizz', 'Eén blik en het hele café is fan.', 49),
  ('Detention', 1, 'Te laat in de les', 'cat', 40, 13, 11, 'cards/detention-1.jpg', 'De wekker ging af. Hij niet.', null, null, null),
  ('Detention', 2, 'Kater van de eeuw', 'cat', 40, 14, 12, 'cards/detention-2.jpg', 'Nooit meer drinken. Tot vrijdag.', null, null, null),
  ('Detention', 3, 'Blauwtje', 'cat', 45, 13, 8, 'cards/detention-3.jpg', 'Ze had "een vriend". Natuurlijk.', null, null, null),
  ('Detention', 4, 'Gsm afgepakt', 'cat', 50, 14, 9, 'cards/detention-4.jpg', 'Krijg je terug op het einde van het jaar.', null, null, null),
  ('Detention', 5, 'Strafstudie', 'cat', 50, 10, 7, 'cards/detention-5.jpg', 'Honderd keer schrijven: ik zal de Wordle oplossen.', null, null, null),
  ('Detention', 6, 'Verloren bij beer pong', 'cat', 41, 13, 10, 'cards/detention-6.jpg', 'Alle bekers. Allemaal.', null, null, null),
  ('Detention', 7, 'Laatste trein gemist', 'cat', 50, 10, 9, 'cards/detention-7.jpg', 'Slaapt vannacht op de bank van iemand anders.', null, null, null),
  ('Detention', 8, 'Rage Quit', 'cat', 51, 10, 9, 'cards/detention-8.jpg', 'De controller heeft het niet overleefd.', null, null, null),
  ('Detention', 9, 'Ingedommeld in de aula', 'cat', 46, 11, 8, 'cards/detention-9.jpg', 'Wakker geworden in een andere les.', null, null, null)
on conflict (person, slot) do update set
  name = excluded.name, rarity = excluded.rarity, hp = excluded.hp, attack = excluded.attack,
  defense = excluded.defense, image_url = excluded.image_url, flavor_text = excluded.flavor_text,
  special_name = excluded.special_name, special_desc = excluded.special_desc, special_power = excluded.special_power;
