-- =====================================================================
-- RIZZ ACADEMY: alle kaarten (126 kaarten)
-- 13 vrienden x 9 kaarten (slot 1-6 common, 7-8 epic, 9 legendary)
-- + 9 Detention-kaarten (troostkaarten, rarity 'cat').
--
-- Gebruik: Supabase -> SQL Editor -> nieuwe query -> dit VOLLEDIGE bestand plakken -> Run.
-- Kies bij de waarschuwing "Run without RLS".
-- Veilig om opnieuw uit te voeren: bestaande kaarten worden bijgewerkt, niet dubbel aangemaakt.
-- Afbeeldingen: cards/<naam>-<slot>.jpg (zonder afbeelding toont de site een varsity-letter).
-- Gegenereerd door tools/maak-kaarten.py.
-- =====================================================================
insert into public.cards (person, slot, name, rarity, hp, attack, defense, image_url, flavor_text, special_name, special_desc, special_power) values
  ('Arthuur', 1, 'Fisheye Arthuur', 'common', 65, 17, 13, 'cards/arthuur-1.jpg', 'Kijkt recht in je ziel. En in je camera.', null, null, null),
  ('Arthuur', 2, 'Stockfoto Arthuur', 'common', 71, 23, 16, 'cards/arthuur-2.jpg', 'Stond ooit in een brochure. Niemand weet welke.', null, null, null),
  ('Arthuur', 3, 'Nachtploeg Arthuur', 'common', 68, 20, 18, 'cards/arthuur-3.jpg', 'Eén pintje. Het zevende.', null, null, null),
  ('Arthuur', 4, 'Pruillip Arthuur', 'common', 57, 24, 17, 'cards/arthuur-4.jpg', 'De drive-thru zei: de frietmachine is stuk.', null, null, null),
  ('Arthuur', 5, 'Hawaii Hydratatie', 'common', 63, 17, 14, 'cards/arthuur-5.jpg', 'Dorstig. Altijd. Overal.', null, null, null),
  ('Arthuur', 6, 'Pokerface Arthuur', 'common', 62, 20, 11, 'cards/arthuur-6.jpg', 'Hij weet iets. Hij zegt het niet.', null, null, null),
  ('Arthuur', 7, 'Front Row Arthuur', 'epic', 87, 29, 21, 'cards/arthuur-7.jpg', 'Hij hoorde de drop. De drop hoorde hem ook.', null, null, null),
  ('Arthuur', 8, 'Stella Sommelier', 'epic', 80, 24, 22, 'cards/arthuur-8.jpg', 'Proeft niet. Inhaleert.', null, null, null),
  ('Arthuur', 9, 'Hedge of Fame Arthuur', 'legendary', 96, 39, 24, 'cards/arthuur-9.jpg', 'Kalendermodel van juni, juli én augustus.', 'Schortje van Schaamte', 'Verblindt de tegenstander met pure zelfzekerheid.', 55),
  ('Casper', 1, 'Breaking News Casper', 'common', 58, 16, 15, 'cards/casper-1.jpg', '"Ja mama, ik ben al wakker." Het is 15u.', null, null, null),
  ('Casper', 2, 'Afterparty Casper', 'common', 67, 17, 14, 'cards/casper-2.jpg', 'Laatste uit het café. Hij is de uitbater.', null, null, null),
  ('Casper', 3, 'Mini-Hoedje Casper', 'common', 66, 20, 15, 'cards/casper-3.jpg', 'Het hoedje is klein. Het ego niet.', null, null, null),
  ('Casper', 4, 'Gym Bro Casper', 'common', 57, 17, 11, 'cards/casper-4.jpg', 'Bulkseizoen. Het hele jaar door.', null, null, null),
  ('Casper', 5, 'Veiligheid Eerst', 'common', 75, 17, 10, 'cards/casper-5.jpg', 'Draagt een helm. Binnen. Je weet maar nooit.', null, null, null),
  ('Casper', 6, 'Shock Value Casper', 'common', 56, 18, 15, 'cards/casper-6.jpg', 'Zag net de rekening van zijn eigen café.', null, null, null),
  ('Casper', 7, 'Summit Scream', 'epic', 90, 27, 21, 'cards/casper-7.jpg', 'Bereikte de top. Vertelde het aan de hele vallei.', null, null, null),
  ('Casper', 8, 'Tinkerbell Casper', 'epic', 91, 26, 23, 'cards/casper-8.jpg', 'Strooit geen feeënstof. Strooit rondjes.', null, null, null),
  ('Casper', 9, 'Hedge of Fame Casper', 'legendary', 107, 33, 23, 'cards/casper-9.jpg', 'Huisdier niet inbegrepen.', 'Reismand-Defensie', 'Niemand weet wat erachter zit. Niemand wil het weten.', 47),
  ('Gerben', 1, 'Gerben in Shock', 'common', 55, 22, 13, 'cards/gerben-1.jpg', 'Zag net wat een holo Charizard kost.', null, null, null),
  ('Gerben', 2, 'Schuimparty Gerben', 'common', 75, 19, 13, 'cards/gerben-2.jpg', 'Wellness is ook facility management.', null, null, null),
  ('Gerben', 3, 'Zwarte Hoed Gerben', 'common', 62, 22, 18, 'cards/gerben-3.jpg', 'Kwam als cowboy. Vertrok als legende.', null, null, null),
  ('Gerben', 4, 'Mini Gerben', 'common', 71, 19, 10, 'cards/gerben-4.jpg', 'Al als kleuter een verzamelaar. Van snoep.', null, null, null),
  ('Gerben', 5, 'Neus voor Zaken', 'common', 58, 14, 11, 'cards/gerben-5.jpg', 'Ruikt een zeldzame kaart op tien meter.', null, null, null),
  ('Gerben', 6, 'Zomerkamp Gerben', 'common', 60, 24, 11, 'cards/gerben-6.jpg', 'Monitor van het jaar. Volgens zichzelf.', null, null, null),
  ('Gerben', 7, 'Kerststal Crasher', 'epic', 90, 26, 17, 'cards/gerben-7.jpg', 'De vierde koning. Bracht geen goud, wel rizz.', null, null, null),
  ('Gerben', 8, 'El Tequila Gerben', 'epic', 78, 26, 21, 'cards/gerben-8.jpg', 'Eén shot en hij staat in de kamer.', null, null, null),
  ('Gerben', 9, 'Hedge of Fame Gerben', 'legendary', 110, 40, 22, 'cards/gerben-9.jpg', 'Rood staat hem. Vooral strategisch.', 'Rode Lap', 'Werkt als een stier op elke tegenstander.', 49),
  ('Jakov', 1, 'Valpartij Jakov', 'common', 65, 14, 10, 'cards/jakov-1.jpg', 'Op zijn bek gegaan. Opgestaan. Snap gestuurd.', null, null, null),
  ('Jakov', 2, 'Hoodie Goblin', 'common', 62, 18, 12, 'cards/jakov-2.jpg', 'Komt enkel ''s nachts buiten. Voor chips.', null, null, null),
  ('Jakov', 3, 'Smirk Jakov', 'common', 67, 23, 15, 'cards/jakov-3.jpg', 'Weet dat hij gelijk heeft. Ook als dat niet zo is.', null, null, null),
  ('Jakov', 4, 'Stadion Jakov', 'common', 56, 20, 15, 'cards/jakov-4.jpg', 'Kwam voor de match. Bleef voor de camera.', null, null, null),
  ('Jakov', 5, 'Junior Wielrenner', 'common', 57, 18, 16, 'cards/jakov-5.jpg', 'Op zijn tiende al een sponsor: een boekhouder.', null, null, null),
  ('Jakov', 6, 'Middenstip Jakov', 'common', 59, 17, 13, 'cards/jakov-6.jpg', 'Denkt na over het leven. Op de middenstip.', null, null, null),
  ('Jakov', 7, 'Piste Beest', 'epic', 84, 27, 19, 'cards/jakov-7.jpg', 'Rondjes draaien? Hij doet het professioneel.', null, null, null),
  ('Jakov', 8, 'Glitch Jakov', 'epic', 89, 32, 24, 'cards/jakov-8.jpg', 'De camera heeft het opgegeven.', null, null, null),
  ('Jakov', 9, 'Hedge of Fame Jakov', 'legendary', 108, 38, 23, 'cards/jakov-9.jpg', 'Fiets: 2.000 euro. Kleren: 0 euro.', 'Velo-Schild', 'Blokkeert elke aanval met een achterwiel.', 47),
  ('Jules', 1, 'BeReal Jules', 'common', 61, 17, 16, 'cards/jules-1.jpg', 'Dertien uur te laat. Nog steeds aan het feesten.', null, null, null),
  ('Jules', 2, 'Cocktail Mood', 'common', 58, 15, 18, 'cards/jules-2.jpg', 'Bestelde een cocktail. Kreeg een emmer.', null, null, null),
  ('Jules', 3, 'Close Talker Jules', 'common', 65, 18, 13, 'cards/jules-3.jpg', 'Persoonlijke ruimte? Nooit van gehoord.', null, null, null),
  ('Jules', 4, 'Kerstfeest Jules', 'common', 58, 18, 15, 'cards/jules-4.jpg', 'Hohoho. Ho. Ho. Hij is er nog.', null, null, null),
  ('Jules', 5, 'Chef Jules', 'common', 63, 22, 15, 'cards/jules-5.jpg', 'Kookt enkel pasta. Met volle overtuiging.', null, null, null),
  ('Jules', 6, 'Blut Jules', 'common', 56, 21, 17, 'cards/jules-6.jpg', 'Einde van de maand. Begin van de maand.', null, null, null),
  ('Jules', 7, 'Kampioen Jules', 'epic', 84, 24, 23, 'cards/jules-7.jpg', 'Won ooit een beker. Praat er nog elke dag over.', null, null, null),
  ('Jules', 8, 'Festival Fit', 'epic', 92, 30, 22, 'cards/jules-8.jpg', 'Luipaardprint. Fluoroze. Geen spijt.', null, null, null),
  ('Jules', 9, 'Hedge of Fame Jules', 'legendary', 101, 38, 27, 'cards/jules-9.jpg', 'Sproeit de haag. En zijn zelfvertrouwen.', 'Tuinslang-Straal', 'Spoelt de tegenstander van het veld.', 55),
  ('Luca', 1, 'Lolly Luca', 'common', 60, 23, 12, 'cards/luca-1.jpg', 'Volwassen man. Gigantische lolly. Geen probleem.', null, null, null),
  ('Luca', 2, 'Scheerschuim Luca', 'common', 55, 24, 16, 'cards/luca-2.jpg', 'Heeft één baardhaar. Scheert het met liefde.', null, null, null),
  ('Luca', 3, 'Catalogus Luca', 'common', 69, 15, 10, 'cards/luca-3.jpg', 'Poseert voor een catalogus die niet bestaat.', null, null, null),
  ('Luca', 4, 'Room Service Luca', 'common', 59, 22, 16, 'cards/luca-4.jpg', 'Brengt pintjes rond. Drinkt er onderweg twee.', null, null, null),
  ('Luca', 5, 'Te Laat Luca', 'common', 62, 14, 13, 'cards/luca-5.jpg', 'Officieel genoteerd: te laat. Onofficieel: altijd.', null, null, null),
  ('Luca', 6, 'Rosé Rebel', 'common', 69, 23, 12, 'cards/luca-6.jpg', 'Een glas? Waarvoor?', null, null, null),
  ('Luca', 7, 'Achtergrondfiguur', 'epic', 88, 29, 23, 'cards/luca-7.jpg', 'Kijk niet achter hem. Echt niet.', null, null, null),
  ('Luca', 8, 'Prinses Luca', 'epic', 87, 31, 24, 'cards/luca-8.jpg', 'Birthday girl energy. 365 dagen per jaar.', null, null, null),
  ('Luca', 9, 'Hedge of Fame Luca', 'legendary', 109, 34, 26, 'cards/luca-9.jpg', 'Eén bloem. Eén schop. Nul spijt.', 'Zonnebloem', 'Bloeit open en verblindt iedereen.', 48),
  ('Seppe', 1, 'Denker Seppe', 'common', 72, 23, 12, 'cards/seppe-1.jpg', 'Diep in gedachten. Over frieten.', null, null, null),
  ('Seppe', 2, 'Lampenkap Seppe', 'common', 57, 21, 18, 'cards/seppe-2.jpg', 'Veiligheid boven alles. Ook binnen.', null, null, null),
  ('Seppe', 3, 'Oerkreet Seppe', 'common', 57, 23, 11, 'cards/seppe-3.jpg', 'Het geluid als de Wordle in één keer lukt.', null, null, null),
  ('Seppe', 4, 'Haarreclame Seppe', 'common', 55, 24, 16, 'cards/seppe-4.jpg', 'L''Oréal belde. Hij had geen tijd.', null, null, null),
  ('Seppe', 5, 'Bubbels Seppe', 'common', 69, 22, 13, 'cards/seppe-5.jpg', 'Twee flessen. Eén voor hem. De andere ook.', null, null, null),
  ('Seppe', 6, 'Pintje Pout', 'common', 61, 21, 12, 'cards/seppe-6.jpg', 'Poseert. Drinkt. Herhaalt.', null, null, null),
  ('Seppe', 7, 'Lingerie Lord', 'epic', 89, 27, 20, 'cards/seppe-7.jpg', 'Dresscode: verrassend.', null, null, null),
  ('Seppe', 8, 'LinkedIn Seppe', 'epic', 88, 29, 20, 'cards/seppe-8.jpg', 'Open to work. Open to party.', null, null, null),
  ('Seppe', 9, 'Hedge of Fame Seppe', 'legendary', 107, 32, 25, 'cards/seppe-9.jpg', 'De enige die zijn kleren aanhield.', 'Kratje Kracht', 'Zit op zijn troon en laat de anderen het werk doen.', 48),
  ('Stan Lavaert', 1, 'Stella Stan', 'common', 62, 15, 15, 'cards/stan-lavaert-1.jpg', 'Kalm. Koel. Geen glas nodig.', null, null, null),
  ('Stan Lavaert', 2, 'Hoofdwerk Stan', 'common', 56, 22, 11, 'cards/stan-lavaert-2.jpg', 'Draagt alles op zijn hoofd. Behalve verantwoordelijkheid.', null, null, null),
  ('Stan Lavaert', 3, 'Mini Stan', 'common', 73, 16, 14, 'cards/stan-lavaert-3.jpg', 'Al jong blauw-zwart. Al jong zelfzeker.', null, null, null),
  ('Stan Lavaert', 4, 'Matchday Stan', 'common', 74, 22, 17, 'cards/stan-lavaert-4.jpg', 'Supportert altijd. Voor wie, hangt af van de score.', null, null, null),
  ('Stan Lavaert', 5, 'Party Mouse Stan', 'common', 67, 18, 18, 'cards/stan-lavaert-5.jpg', 'Minnie-oortjes. Maximale energie.', null, null, null),
  ('Stan Lavaert', 6, 'Heineken Stan', 'common', 60, 20, 11, 'cards/stan-lavaert-6.jpg', 'Proost op alles. Ook op dinsdag.', null, null, null),
  ('Stan Lavaert', 7, 'Batstan', 'epic', 91, 28, 21, 'cards/stan-lavaert-7.jpg', 'Niet de held die we nodig hebben. Wel die we verdienen.', null, null, null),
  ('Stan Lavaert', 8, 'Sniper Stan', 'epic', 87, 29, 18, 'cards/stan-lavaert-8.jpg', 'Mikt. Wacht. Mist. Mikt opnieuw.', null, null, null),
  ('Stan Lavaert', 9, 'Don Stan', 'legendary', 102, 34, 28, 'cards/stan-lavaert-9.jpg', 'Hij zegt niet veel. Hij moet niet.', 'Sigarenrook', 'Hult het hele veld in mysterie.', 54),
  ('Stan Sabbe', 1, 'Fisheye Stan S.', 'common', 69, 19, 16, 'cards/stan-sabbe-1.jpg', 'Lacht altijd. Zelfs met tegenwind.', null, null, null),
  ('Stan Sabbe', 2, 'Hoodie Stan S.', 'common', 72, 19, 10, 'cards/stan-sabbe-2.jpg', 'Kijkt onschuldig. Is het niet.', null, null, null),
  ('Stan Sabbe', 3, 'Feestvarken Stan S.', 'common', 59, 23, 16, 'cards/stan-sabbe-3.jpg', 'De nacht van zijn leven. Elke week.', null, null, null),
  ('Stan Sabbe', 4, 'Close Call Stan S.', 'common', 66, 21, 14, 'cards/stan-sabbe-4.jpg', 'Te dichtbij. Altijd te dichtbij.', null, null, null),
  ('Stan Sabbe', 5, 'Festival Stan S.', 'common', 66, 20, 15, 'cards/stan-sabbe-5.jpg', 'Hoedje op. Volume op.', null, null, null),
  ('Stan Sabbe', 6, 'Brilmans Stan S.', 'common', 60, 18, 14, 'cards/stan-sabbe-6.jpg', 'Ziet alles. Onthoudt niets.', null, null, null),
  ('Stan Sabbe', 7, 'XL Stan S.', 'epic', 85, 30, 17, 'cards/stan-sabbe-7.jpg', 'Maat S. Shirt XL. Ego XXL.', null, null, null),
  ('Stan Sabbe', 8, 'Junior Model Stan S.', 'epic', 89, 28, 22, 'cards/stan-sabbe-8.jpg', 'Poseerde als kind al als een topmodel.', null, null, null),
  ('Stan Sabbe', 9, 'Hedge of Fame Stan S.', 'legendary', 102, 35, 26, 'cards/stan-sabbe-9.jpg', 'Klusjesman van het jaar. Zonder werkkledij.', 'Boormachine', 'Boort dwars door elke verdediging.', 48),
  ('Thibault', 1, 'Jungle Thibault', 'common', 62, 19, 11, 'cards/thibault-1.jpg', 'Koning van het bos. Tot de mug kwam.', null, null, null),
  ('Thibault', 2, 'Campingstoel Kampioen', 'common', 65, 15, 16, 'cards/thibault-2.jpg', 'Rust is ook een sport.', null, null, null),
  ('Thibault', 3, 'Tong Thibault', 'common', 62, 15, 11, 'cards/thibault-3.jpg', 'Festivalmodus: geactiveerd.', null, null, null),
  ('Thibault', 4, 'Pasfoto Thibault', 'common', 63, 14, 17, 'cards/thibault-4.jpg', 'Neemt alles serieus. Behalve school.', null, null, null),
  ('Thibault', 5, 'Verkeersgroet Thibault', 'common', 60, 16, 18, 'cards/thibault-5.jpg', 'Groet iedereen op de weg. Op zijn manier.', null, null, null),
  ('Thibault', 6, 'Duim Omhoog Thibault', 'common', 70, 17, 17, 'cards/thibault-6.jpg', 'Alles komt goed. Hij heeft het niet nagekeken.', null, null, null),
  ('Thibault', 7, 'Bar Baron Thibault', 'epic', 91, 27, 18, 'cards/thibault-7.jpg', 'Bestelt voor iedereen. Betaalt voor niemand.', null, null, null),
  ('Thibault', 8, 'Rizz Thibault', 'epic', 87, 26, 20, 'cards/thibault-8.jpg', 'Rizzniveau: Amerikaans.', null, null, null),
  ('Thibault', 9, 'Midnight Streaker', 'legendary', 97, 38, 27, 'cards/thibault-9.jpg', 'Vergat zijn kleren. Niet zijn pint.', 'Volle Maan', 'Licht de hele straat op. Iedereen kijkt weg.', 49),
  ('Thomas', 1, 'Denker Thomas', 'common', 73, 22, 15, 'cards/thomas-1.jpg', 'Overweegt een tweede pint. Besluit: ja.', null, null, null),
  ('Thomas', 2, 'Paparazzi Thomas', 'common', 63, 14, 18, 'cards/thomas-2.jpg', 'Geen foto''s alstublieft. Behalve deze.', null, null, null),
  ('Thomas', 3, 'Strandsprint Thomas', 'common', 63, 21, 18, 'cards/thomas-3.jpg', 'Rent naar de zee. Bedenkt zich.', null, null, null),
  ('Thomas', 4, 'Rally Thomas', 'common', 56, 14, 11, 'cards/thomas-4.jpg', 'Rijbewijs ingetrokken. Plan B.', null, null, null),
  ('Thomas', 5, 'Tong Uit Thomas', 'common', 67, 16, 13, 'cards/thomas-5.jpg', 'Stadsbezoek. Cultuur gesnoven.', null, null, null),
  ('Thomas', 6, 'Bedhead Thomas', 'common', 58, 23, 16, 'cards/thomas-6.jpg', 'Net opgestaan. Om 16u.', null, null, null),
  ('Thomas', 7, 'Diva Thomas', 'epic', 81, 30, 23, 'cards/thomas-7.jpg', 'Haar in een handdoek. Frietjes op het vuur.', null, null, null),
  ('Thomas', 8, 'Gele Trui Thomas', 'epic', 91, 30, 24, 'cards/thomas-8.jpg', 'Won de Tour. In karton.', null, null, null),
  ('Thomas', 9, 'Hedge of Fame Thomas', 'legendary', 109, 32, 22, 'cards/thomas-9.jpg', 'Klaar voor de winter. Niet voor de foto.', 'Sneeuwschep', 'Schept de tegenstander met één beweging van het veld.', 52),
  ('Tuur', 1, 'Knuffelkoning Tuur', 'common', 61, 23, 13, 'cards/tuur-1.jpg', 'Won geen enkele knuffel. Kocht ze allemaal.', null, null, null),
  ('Tuur', 2, 'Blik van Staal', 'common', 62, 19, 17, 'cards/tuur-2.jpg', 'Eén blik. Iedereen stil.', null, null, null),
  ('Tuur', 3, 'Mondmasker Tuur', 'common', 58, 15, 18, 'cards/tuur-3.jpg', 'Draagt zijn mondmasker als kinbeschermer.', null, null, null),
  ('Tuur', 4, 'Blikje Tuur', 'common', 67, 19, 16, 'cards/tuur-4.jpg', 'Hapt naar adem. Hapt naar Jupiler.', null, null, null),
  ('Tuur', 5, 'Selfie Tuur', 'common', 62, 19, 16, 'cards/tuur-5.jpg', 'Zijn goede kant? Alle kanten.', null, null, null),
  ('Tuur', 6, 'Snapchat Tuur', 'common', 56, 19, 12, 'cards/tuur-6.jpg', 'Stuurt deze foto naar zijn crush. Elke keer.', null, null, null),
  ('Tuur', 7, 'Ober Tuur', 'epic', 92, 25, 23, 'cards/tuur-7.jpg', 'Serveert met stijl. Morst met stijl.', null, null, null),
  ('Tuur', 8, 'Rietje Tuur', 'epic', 88, 26, 19, 'cards/tuur-8.jpg', 'Het langste rietje van het terras. Toevallig.', null, null, null),
  ('Tuur', 9, 'Rizz Lord Tuur', 'legendary', 100, 36, 23, 'cards/tuur-9.jpg', 'Kwam met een bandana. Vertrok met een kus.', 'Lippenstiftstempel', 'Markeert de tegenstander voor altijd.', 53),
  ('Wout', 1, 'Zonnebril Wout', 'common', 75, 21, 10, 'cards/wout-1.jpg', 'Coolheid: maximaal. Zicht: minimaal.', null, null, null),
  ('Wout', 2, 'Postkaart Wout', 'common', 71, 22, 10, 'cards/wout-2.jpg', 'Groetjes van zee. Hij heeft het koud.', null, null, null),
  ('Wout', 3, 'Volle Maan Wout', 'common', 55, 23, 18, 'cards/wout-3.jpg', 'Toont zijn beste kant.', null, null, null),
  ('Wout', 4, 'Clubbing Wout', 'common', 56, 19, 16, 'cards/wout-4.jpg', 'Zonnebril ''s nachts. Uit principe.', null, null, null),
  ('Wout', 5, 'Kaalkop Wout', 'common', 73, 22, 18, 'cards/wout-5.jpg', 'Nieuwe kapper. Nieuwe start. Oude kater.', null, null, null),
  ('Wout', 6, 'Bakske Wout', 'common', 72, 20, 15, 'cards/wout-6.jpg', 'Zit op een bak. Zit nooit zonder bak.', null, null, null),
  ('Wout', 7, 'Superbarman Wout', 'epic', 90, 27, 22, 'cards/wout-7.jpg', 'Tapt sneller dan zijn schaduw.', null, null, null),
  ('Wout', 8, 'Business Wout', 'epic', 89, 29, 19, 'cards/wout-8.jpg', 'Heeft een plan. Het plan is drinken.', null, null, null),
  ('Wout', 9, 'Hedge of Fame Wout', 'legendary', 96, 33, 22, 'cards/wout-9.jpg', 'Tuinman van het jaar. Kruiwagen inbegrepen.', 'Kruiwagen-Charge', 'Rijdt dwars door de tegenstander.', 49),
  ('Detention', 1, 'Te laat in de les', 'cat', 40, 13, 11, 'cards/detention-1.jpg', 'De wekker ging af. Hij niet.', null, null, null),
  ('Detention', 2, 'Kater van de eeuw', 'cat', 40, 14, 12, 'cards/detention-2.jpg', 'Nooit meer drinken. Tot vrijdag.', null, null, null),
  ('Detention', 3, 'Blauwtje', 'cat', 45, 13, 8, 'cards/detention-3.jpg', 'Ze had "een vriend". Natuurlijk.', null, null, null),
  ('Detention', 4, 'Gsm afgepakt', 'cat', 50, 14, 9, 'cards/detention-4.jpg', 'Krijg je terug op het einde van het jaar.', null, null, null),
  ('Detention', 5, 'Strafstudie', 'cat', 50, 10, 7, 'cards/detention-5.jpg', 'Honderd keer schrijven: ik zal de Wordle oplossen.', null, null, null),
  ('Detention', 6, 'Verloren bij beer pong', 'cat', 41, 13, 10, 'cards/detention-6.jpg', 'Alle bekers. Allemaal.', null, null, null),
  ('Detention', 7, 'Laatste trein gemist', 'cat', 50, 10, 9, 'cards/detention-7.jpg', 'Slaapt vannacht op de bank van iemand anders.', null, null, null),
  ('Detention', 8, 'Rage Quit', 'cat', 51, 10, 9, 'cards/detention-8.jpg', 'De controller heeft het niet overleefd.', null, null, null),
  ('Detention', 9, 'Ingedommeld in de aula', 'cat', 46, 11, 8, 'cards/detention-9.jpg', 'Wakker geworden in een andere les.', null, null, null)
on conflict (person, slot) do update set
  name = excluded.name, rarity = excluded.rarity, hp = excluded.hp, attack = excluded.attack,
  defense = excluded.defense, image_url = excluded.image_url, flavor_text = excluded.flavor_text,
  special_name = excluded.special_name, special_desc = excluded.special_desc, special_power = excluded.special_power;
